# User Config
# ===========
# fill/change these fields to match your own.

# Identity
# --------

title:       Lazy programmer
description: Life is always under maintenance

logo:  "/assets/img/logo.jpg"
cover: "/assets/img/cover.jpg"

baseurl: "/"
url:     "https://taneekpet.github.io"

owner:  taneekpet
rights: All Right Reserved


# Social & Sharing
# ----------------

google:
  analytics:
  verification:

facebook:
  username:
  app_id:

twitter:
  username:
  large_img: sometimes

disqus:
  username:


# Content Format
# --------------

timezone: Asia/Bangkok
show_time: true                         #TODO show time alongside date?
paginate: 3
mathjax:  true

theme:
  highlight: github               

# Engine Config
# =============
# you shouldn't change this unless you really know what you're doing.

collections:
  projects:
    output: true
  drafts:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: drafts
    values:
      layout: draft

permalink: date
paginate_path: "/posts/page:num"

sass:
  sass_dir: "_sass/"
  style: compressed

exclude:
  - README.md
  - LICENSE.txt

plugins:
  - jekyll-sitemap
  - jekyll-paginate

empty_array: []
